### Create a new user
POST http://localhost:3000/api/v1/users/signup
Content-Type: application/json

{
  "username": "Newman",
  "email": "newman.man@man.com",
  "password": "pass"
}

### Find a particular user with a given ID
GET http://localhost:3000/api/v1/users/2
### Find all users with a given email
GET http://localhost:3000/api/v1/users?email=example@testing.com

### Delete a user with a given id
DELETE http://localhost:3000/api/v1/users/45

### Update a user
PATCH http://localhost:3000/api/v1/users/45
content-type: application/json

{
  "email": "update-second-time@testing.com"
}
