### Register a new user
POST http://localhost:3000/api/v1/users/register
Content-Type: application/json

{
  "username": "Miss Admin",
  "email": "miss-admin@sophon.com",
  "password": "pa55ntM4tt3r"
}

### Authenticate user
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
  "email": "cookie-monster@sophon.com",
  "password": "pa55ntM4tt3r"
}

### Get authenticated user
GET http://localhost:3000/api/v1/users/whoami

### Logout
POST http://localhost:3000/api/v1/users/logout

### Find a particular user with a given ID
GET http://localhost:3000/api/v1/users/9
### Find all users with a given email
GET http://localhost:3000/api/v1/users?email=example@testing.com

### Delete a user with a given id
DELETE http://localhost:3000/api/v1/users/45

### Update a user
PATCH http://localhost:3000/api/v1/users/45
content-type: application/json

{
  "email": "update-second-time@testing.com"
}

